site_name: Cristian Rodríguez Canto
site_description: Chilean Software Engineer | Projects, Articles, and CV
site_url: https://c11r11.github.io
site_dir: dist

theme:
  name: material
  custom_dir: overrides # Add this line!
  palette:
    primary: white
    accent: white
  font:
    text: Charter
    code: Roboto Mono
  features:
    - navigation.sections
    - navigation.top
  favicon: assets/favicon.ico

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Blog: articles/index.md
  - CV: assets/cv.pdf

extra:
  analytics:
    provider: google
    property: G-8CBZW9T5YM # Replace with your actual ID